"""Ticket schema and monthly number sequence (P1-CAP-01)."""
from alembic import op
import sqlalchemy as sa

revision = "cap01"
down_revision = "cusprd07"
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_number_sequence',
    sa.Column('period', sa.String(length=6), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('period')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_no', sa.String(length=32), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('ticket_type_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('course_or_exam_id', sa.Integer(), nullable=True),
    sa.Column('product_instance_id', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('browser_device', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('exam_or_course_context', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('symptom_id', sa.Integer(), nullable=True),
    sa.Column('service_stage_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=2), nullable=True),
    sa.Column('impact_scope', sa.String(length=50), nullable=True),
    sa.Column('severity_overridden_reason', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('current_tier', sa.Integer(), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('first_response_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('root_cause_code_id', sa.Integer(), nullable=True),
    sa.Column('resolution_code_id', sa.Integer(), nullable=True),
    sa.Column('resolution_detail', sa.Text(), nullable=True),
    sa.Column('kb_article_id', sa.Integer(), nullable=True),
    sa.Column('master_ticket_id', sa.Integer(), nullable=True),
    sa.Column('sla_policy_id', sa.Integer(), nullable=True),
    sa.Column('sla_breached', sa.Boolean(), nullable=False),
    sa.Column('workload_points', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reopen_count', sa.Integer(), nullable=False),
    sa.Column('is_exam_window', sa.Boolean(), nullable=False),
    sa.Column('legacy_case_no', sa.String(length=100), nullable=True),
    sa.CheckConstraint("severity IS NULL OR severity IN ('S1','S2','S3','S4')", name='ck_ticket_severity'),
    sa.CheckConstraint("status IN ('DRAFT', 'NEW', 'IN_PROGRESS', 'PENDING_CUSTOMER', 'PENDING_EXTERNAL', 'RESOLVED', 'CLOSED', 'REOPENED', 'DUPLICATE', 'CANCELLED')", name='ck_ticket_status'),
    sa.CheckConstraint('current_tier IS NULL OR current_tier IN (0,1,2)', name='ck_ticket_tier'),
    sa.CheckConstraint('reopen_count >= 0', name='ck_ticket_reopen_count'),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['problem_types.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['course_or_exam_id'], ['course_or_exam.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['master_ticket_id'], ['ticket.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_instance_id'], ['product_instance.id'], ),
    sa.ForeignKeyConstraint(['resolution_code_id'], ['solution_codes.id'], ),
    sa.ForeignKeyConstraint(['root_cause_code_id'], ['cause_codes.id'], ),
    sa.ForeignKeyConstraint(['service_stage_id'], ['service_stages.id'], ),
    sa.ForeignKeyConstraint(['sla_policy_id'], ['sla_policies.id'], ),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], ),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_assignee_id'), 'ticket', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_ticket_contact_id'), 'ticket', ['contact_id'], unique=False)
    op.create_index(op.f('ix_ticket_organization_id'), 'ticket', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ticket_owner_id'), 'ticket', ['owner_id'], unique=False)
    op.create_index(op.f('ix_ticket_product_instance_id'), 'ticket', ['product_instance_id'], unique=False)
    op.create_index(op.f('ix_ticket_reported_at'), 'ticket', ['reported_at'], unique=False)
    op.create_index(op.f('ix_ticket_status'), 'ticket', ['status'], unique=False)
    op.create_index(op.f('ix_ticket_ticket_no'), 'ticket', ['ticket_no'], unique=True)
    # ### end Alembic commands ###

def downgrade():
    op.drop_table("ticket")
    op.drop_table("ticket_number_sequence")
