"""Converge CUS/PRD and ADM on the ADM product/module catalogue.

Legacy catalogue tables are retained as rollback snapshots, not used by APIs.
Data-dependent reconciliation requires an online migration.
"""
from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa

revision = "cusadm01"
down_revision = ("cusprd08", "c4e7f1a9b2d3")
branch_labels = None
depends_on = None
NAMING = {"fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s"}


def _product_fk(target):
    # Reflect names generated by MariaDB; SQLite's original FK is unnamed.
    return next(fk["name"] or "fk_product_instance_product_id_" + target
                for fk in sa.inspect(op.get_bind()).get_foreign_keys("product_instance")
                if fk["constrained_columns"] == ["product_id"])


def upgrade():
    bind = op.get_bind()
    if op.get_context().as_sql:
        raise RuntimeError("cusadm01 reconciles existing data and requires online migration")
    metadata = sa.MetaData()
    legacy = sa.Table("product", metadata, autoload_with=bind)
    legacy_modules = sa.Table("product_module", metadata, autoload_with=bind)
    old_products = bind.execute(sa.select(legacy)).mappings().all()
    old_modules = bind.execute(sa.select(legacy_modules)).mappings().all()
    # Refuse ambiguous/destructive conversions before changing the schema.
    names = [row["name"].casefold() for row in old_products]
    if len(names) != len(set(names)) or any(len(row["name"]) > 150 for row in old_products):
        raise RuntimeError("Reconcile duplicate or overlong legacy product names before migration")
    if any(len(row["name"]) > 100 for row in old_modules):
        raise RuntimeError("Reconcile legacy module names longer than 100 characters before migration")
    for row in old_products:
        # Honor the database's real collation as well as Python casefolding.
        count = bind.scalar(sa.select(sa.func.count()).select_from(legacy).where(legacy.c.name == row["name"]))
        if count != 1:
            raise RuntimeError("Reconcile legacy product names that collide under the database collation")
    for row in old_modules:
        count = bind.scalar(sa.select(sa.func.count()).select_from(legacy_modules).where(
            legacy_modules.c.product_id == row["product_id"], legacy_modules.c.name == row["name"]))
        if count != 1:
            raise RuntimeError("Reconcile duplicate legacy module names before migration")
    with op.batch_alter_table("products") as batch:
        batch.add_column(sa.Column("code", sa.String(50), nullable=True))
        batch.add_column(sa.Column("default_team_id", sa.Integer(), nullable=True))
        batch.create_foreign_key("fk_products_default_team", "teams", ["default_team_id"], ["id"])
        batch.create_index("ix_products_default_team_id", ["default_team_id"])
    with op.batch_alter_table("modules") as batch:
        batch.add_column(sa.Column("code", sa.String(50), nullable=True))
    products = sa.Table("products", sa.MetaData(), autoload_with=bind)
    modules = sa.Table("modules", sa.MetaData(), autoload_with=bind)
    def fresh_code(stem, used):
        value, suffix = stem, 0
        while value in used:
            suffix += 1
            value = f"{stem}-{suffix}"
        used.add(value)
        return value
    used = {row['code'] for row in old_products}
    for row in bind.execute(sa.select(products)).mappings().all():
        bind.execute(products.update().where(products.c.id == row["id"]).values(
            code=fresh_code(f"adm-p-{row['id']}", used)))
    used = {row['code'] for row in old_modules}
    for row in bind.execute(sa.select(modules)).mappings().all():
        bind.execute(modules.update().where(modules.c.id == row["id"]).values(
            code=fresh_code(f"adm-m-{row['id']}", used)))
    op.create_table("cusprd_product_id_map",
                    sa.Column("legacy_id", sa.Integer(), primary_key=True),
                    sa.Column("canonical_id", sa.Integer(), nullable=False, unique=True))
    mapping = sa.Table("cusprd_product_id_map", sa.MetaData(), autoload_with=bind)
    now = datetime.now(timezone.utc).replace(tzinfo=None)
    # Existing ADM writers omit registry codes; DB defaults keep them compatible.
    code_default = sa.text("(lower(hex(randomblob(16))))") if bind.dialect.name == "sqlite" else sa.text("(UUID())")
    ids = {}
    for row in old_products:
        match = bind.execute(sa.select(products).where(products.c.name == row["name"])).mappings().first()
        if match:
            new_id = match["id"]
            # ADM values remain authoritative for active state/name; preserve registry code/team.
            bind.execute(products.update().where(products.c.id == new_id).values(
                code=row["code"], default_team_id=row["default_team_id"]))
        else:
            result = bind.execute(products.insert().values(name=row["name"], code=row["code"],
                is_active=row["is_active"], default_team_id=row["default_team_id"], created_at=now, updated_at=now))
            new_id = result.inserted_primary_key[0]
        ids[row["id"]] = new_id
        bind.execute(mapping.insert().values(legacy_id=row["id"], canonical_id=new_id))
    for row in old_modules:
        product_id = ids[row["product_id"]]
        match = bind.execute(sa.select(modules).where(modules.c.product_id == product_id,
                                                     modules.c.name == row["name"])).mappings().first()
        if match:
            bind.execute(modules.update().where(modules.c.id == match["id"]).values(code=row["code"]))
        else:
            bind.execute(modules.insert().values(product_id=product_id, name=row["name"],
                code=row["code"], is_active=row["is_active"], created_at=now, updated_at=now))
    with op.batch_alter_table("products") as batch:
        batch.alter_column("code", existing_type=sa.String(50), nullable=False, server_default=code_default)
        batch.create_unique_constraint("uq_products_code", ["code"])
    with op.batch_alter_table("modules") as batch:
        batch.alter_column("code", existing_type=sa.String(50), nullable=False, server_default=code_default)
        batch.create_unique_constraint("uq_modules_product_code", ["product_id", "code"])
    fk = _product_fk("product")
    with op.batch_alter_table("product_instance", naming_convention=NAMING) as batch:
        batch.drop_constraint(fk, type_="foreignkey")
    instances = sa.Table("product_instance", sa.MetaData(), autoload_with=bind)
    # Temporary negative IDs avoid transient unique-key collisions on swaps.
    if ids:
        bind.execute(instances.update().values(product_id=-instances.c.product_id))
        bind.execute(instances.update().values(product_id=sa.case(
            {-old: new for old, new in ids.items()}, value=instances.c.product_id)))
    with op.batch_alter_table("product_instance") as batch:
        batch.create_foreign_key("fk_instance_adm_product", "products", ["product_id"], ["id"])


def downgrade():
    bind = op.get_bind()
    mapping = sa.Table("cusprd_product_id_map", sa.MetaData(), autoload_with=bind)
    ids = {row.canonical_id: row.legacy_id for row in bind.execute(sa.select(mapping))}
    instances = sa.Table("product_instance", sa.MetaData(), autoload_with=bind)
    active_ids = set(bind.execute(sa.select(instances.c.product_id).distinct()).scalars())
    if not active_ids.issubset(ids):
        raise RuntimeError("Cannot rollback: new canonical products have instances; export/reconcile data first")
    with op.batch_alter_table("product_instance") as batch:
        batch.drop_constraint("fk_instance_adm_product", type_="foreignkey")
    if ids:
        bind.execute(instances.update().values(product_id=-instances.c.product_id))
        bind.execute(instances.update().values(product_id=sa.case(
            {-old: new for old, new in ids.items()}, value=instances.c.product_id)))
    with op.batch_alter_table("product_instance") as batch:
        batch.create_foreign_key("fk_product_instance_product_id_product", "product", ["product_id"], ["id"])
    op.drop_table("cusprd_product_id_map")
    with op.batch_alter_table("modules") as batch:
        batch.drop_constraint("uq_modules_product_code", type_="unique")
        batch.drop_column("code")
    with op.batch_alter_table("products") as batch:
        batch.drop_constraint("fk_products_default_team", type_="foreignkey")
        batch.drop_index("ix_products_default_team_id")
        batch.drop_constraint("uq_products_code", type_="unique")
        batch.drop_column("default_team_id")
        batch.drop_column("code")
